CREATE TABLE PAYMENT (
    ID VARCHAR(36),
    USER_ID VARCHAR(36) NOT NULL,
    USER_MAIL VARCHAR(124) NOT NULL,
    AMOUNT decimal(19,2) NOT NULL,
    STATUS VARCHAR(124) NOT NULL,
    REQUESTED_ON TIMESTAMP NOT NULL,
    FINISHED_ON TIMESTAMP,
    PRIMARY KEY(ID)
);
