CREATE TABLE USER (
    USERNAME VARCHAR(124) NOT NULL,
    EMAIL VARCHAR(124) NOT NULL,
    PASSWORD VARCHAR(124) NOT NULL,
    AUTHORITY VARCHAR(124) NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    PRIMARY KEY(USERNAME)
);
CREATE TABLE CASINO_USER (
    ID INT NOT NULL PRIMARY KEY,
    NICKNAME VARCHAR(124) NOT NULL,
    BALANCE DOUBLE,
    IS_ACTIVE BOOLEAN,
    FIRST_NAME VARCHAR(124),
    SECOND_NAME VARCHAR(124),
    BIRTH_DATE DATE,
    COUNTRY VARCHAR(124)
);